import React from "react";

export default function Home() {
  return (
    <div>
      <p>
        HI THERE, MY NAME IS JAVIER LASSUS. IM A WEB DEVELOPER EAGER TO LEARN
        AND BUILD NEW THINGS.
      </p>
      <p>
        FOR THE PAST YEAR LIFE HAS BEEN REALLY HARD FOR MANY PEOPLE AS SAME AS
        ME, I LOST MY JOB AS A CABLE TECHNICIAN.AFTER ALMOST EIGHT MONTHS OF
        UNEMPLOYMENT AND NOT BEING ABLE TO FIND ANYTHING THAT WOULD GIVE ANY
        MEANING TO MY LIFE, I WAS RECOMMENDEN TO LOOK INTO WEB DEVELOPMENT AND
        THE REST IS HISTORY AS I HAVE FALLEN IN LOVE WITH THIS NEW WORLD I JUST
        DISCOVER
      </p>
    </div>
  );
}
