import React from "react";
import "../Components.scss";

export default function ToolIcons() {
  return (
    <div className="tool">
      <div className="tool--cont">
        <img
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
          alt="css3"
          width="40"
          height="40"
        />
        <img
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
          alt="express"
          width="40"
          height="40"
        />
        <img
          src="https://www.vectorlogo.zone/logos/figma/figma-icon.svg"
          alt="figma"
          width="40"
          height="40"
        />
        <img
          src="https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg"
          alt="firebase"
          width="40"
          height="40"
        />
      </div>
      <div className="tool--cont">
        <img
          src="https://www.vectorlogo.zone/logos/google_cloud/google_cloud-icon.svg"
          alt="gcp"
          width="40"
          height="40"
        />
        <img
          src="https://www.vectorlogo.zone/logos/heroku/heroku-icon.svg"
          alt="heroku"
          width="40"
          height="40"
        />
        <img
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
          alt="html5"
          width="40"
          height="40"
        />
        <img
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
          alt="javascript"
          width="40"
          height="40"
        />
      </div>
      <div className="tool--cont">
        <img
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
          alt="mongodb"
          width="40"
          height="40"
        />
        <img
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
          alt="mysql"
          width="40"
          height="40"
        />
        <img
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
          alt="nodejs"
          width="40"
          height="40"
        />
        <img
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/photoshop/photoshop-line.svg"
          alt="photoshop"
          width="40"
          height="40"
        />
      </div>
      <div className="tool--cont">
        <img
          src="https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg"
          alt="postman"
          width="40"
          height="40"
        />
        <img
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
          alt="react"
          width="40"
          height="40"
        />
        <img
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg"
          alt="sass"
          width="40"
          height="40"
        />
        <img
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/vuejs/vuejs-original-wordmark.svg"
          alt="vuejs"
          width="40"
          height="40"
        />
      </div>
    </div>
  );
}
